const DISPOSABLE_DOMAINS = new Set([
  // Provided in requirements
  "mailinator.com",
  "tempmail.com",
  "guerrillamail.com",
  "throwaway.email",
  "yopmail.com",
  "10minutemail.com",
  "trashmail.com",
  "fakeinbox.com",
  "sharklasers.com",
  "guerrillamail.info",
  "grr.la",
  "dispostable.com",
  "maildrop.cc",
  "temp-mail.org",
  // Additional 50+ common disposable domains
  "guerrillamailblock.com",
  "spam4.me",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "trashmail.at",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.xyz",
  "mailnull.com",
  "mailnesia.com",
  "mailnull.com",
  "spamfree24.org",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "getnada.com",
  "jetable.fr.nf",
  "jetable.net",
  "jetable.org",
  "nomail.xl.cx",
  "tnef.com",
  "throwam.com",
  "throwam.com",
  "spamgrap.com",
  "spamhereplease.com",
  "spamspot.com",
  "tempr.email",
  "tempinbox.com",
  "tempinbox.co.uk",
  "temp-mail.ru",
  "temp-mail.io",
  "tempail.com",
  "tempemail.co",
  "tempemail.net",
  "tempemail.org",
  "temporaryemail.net",
  "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymail.org",
  "temporarymailaddress.com",
  "throwablemail.com",
  "throwam.com",
  "throwawayemailaddress.com",
  "trbvm.com",
  "trbvn.com",
  "trillianpro.com",
  "turual.com",
  "twinmail.de",
  "upermail.com",
  "vomoto.com",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wetrainbayarea.com",
  "wh4f.org",
  "whatpaas.com",
  "whyspam.me",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "wilemail.com",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "xtremedada.com",
  "yep.it",
  "yogamaven.com",
  "yopmail.fr",
  "yopmail.pp.ua",
  "yourdomain.com",
  "z1p.biz",
  "zebins.com",
  "zebins.eu",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.net",
  "zoemail.org",
  "zomg.info",
  "binkmail.com",
  "bobmail.info",
  "bodhi.lawlita.com",
  "bofthew.com",
  "bootybay.de",
  "boun.cr",
  "bouncr.com",
  "breakthru.com",
  "brefmail.com",
  "brennendesreich.de",
  "broadbandninja.com",
  "brubble.biz",
  "bspamfree.org",
  "buffemail.com",
  "bugmenot.com",
  "bumpymail.com",
  "cachedot.net",
  "casualdx.com",
  "cefnogi.co.uk",
  "centermail.com",
  "centermail.net",
  "chammy.info",
  "chogmail.com",
  "choicemail1.com",
  "civvic.ro",
  "clandest.in",
  "classesmail.com",
  "cleaninbox.net",
  "clepites.ro",
  "clrmail.com",
  "cnamed.com",
  "cock.li",
  "cocoro.uk",
  "cocorusse.fr",
  "codedatum.com",
  "crapmail.org",
  "crastination.de",
  "crazymailing.com",
  "cubiclink.com",
  "curryworld.de",
  "cust.in",
  "dacoolest.com",
  "daintly.com",
  "dakingsmail.com",
  "dandikmail.com",
  "daymailonline.com",
  "dbunker.com",
  "dcemail.com",
  "deadaddress.com",
  "deadletter.ga",
  "deagot.com",
  "deals.burner.mobi",
  "deezerdiscounts.com",
  "delayload.com",
  "delayload.net",
  "desertshiningstars.com",
  "despam.it",
  "despammed.com",
  "devnullmail.com",
  "dfgh.net",
  "digitalsanctuary.com",
  "dingbone.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "discardmail.ga",
  "discardmail.gq",
  "discardmail.ml",
  "discardmail.tk",
  "dispostable.com",
  "disposableaddress.com",
  "disposableemailaddresses.com",
  "disposableinbox.com",
  "dispose.it",
  "dm.w3internet.co.uk",
  "domozmail.com",
  "donemail.ru",
  "dontreg.com",
  "dontsendmespam.de",
  "dooiiy.com",
  "drdrb.com",
  "drdrb.net",
  "droplar.com",
  "droplister.com",
  "dropmail.me",
  "dumpandfuck.com",
  "dumpmail.de",
  "dumpyemail.com",
  "e4ward.com",
  "easytrashmail.com",
  "email60.com",
  "emaildienst.de",
  "emailgo.de",
  "emailias.com",
  "emailigo.de",
  "emailinfive.com",
  "emailisvalid.com",
  "emailmiser.com",
  "emailsensei.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "emailtemporaneo.com",
  "emailto.de",
  "emailwarden.com",
  "emailx.at.hm",
  "emailxfer.com",
  "emeil.in",
  "emeil.ir",
  "emz.net",
  "enterto.com",
  "ephemail.net",
  "etranquil.com",
  "etranquil.net",
  "etranquil.org",
  "evopo.com",
  "explodemail.com",
  "express.net.ua",
  "extremail.ru",
  "eyepaste.com",
]);

const TRUSTED_DOMAINS = new Set([
  "gmail.com",
  "googlemail.com",
  "yahoo.com",
  "yahoo.co.uk",
  "yahoo.co.in",
  "yahoo.com.au",
  "yahoo.fr",
  "yahoo.de",
  "yahoo.es",
  "yahoo.it",
  "yahoo.ca",
  "yahoo.com.br",
  "outlook.com",
  "outlook.co.uk",
  "outlook.in",
  "hotmail.com",
  "hotmail.co.uk",
  "hotmail.fr",
  "hotmail.de",
  "hotmail.es",
  "hotmail.it",
  "hotmail.com.br",
  "icloud.com",
  "me.com",
  "mac.com",
  "protonmail.com",
  "protonmail.ch",
  "proton.me",
  "aol.com",
  "zoho.com",
  "zohomail.com",
  "live.com",
  "live.co.uk",
  "msn.com",
  "yandex.com",
  "yandex.ru",
  "mail.com",
  "email.com",
  "fastmail.com",
  "fastmail.fm",
  "tutanota.com",
  "tutanota.de",
  "tutamail.com",
  "hey.com",
  "pm.me",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.toLowerCase().split("@")[1];
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}

export function validateEmailDomain(
  email: string
): { valid: boolean; reason?: string } {
  const parts = email.toLowerCase().split("@");
  if (parts.length !== 2 || !parts[1]) {
    return { valid: false, reason: "Invalid email format" };
  }

  const domain = parts[1];

  // Fast-path for well-known trusted providers
  if (TRUSTED_DOMAINS.has(domain)) {
    return { valid: true };
  }

  if (DISPOSABLE_DOMAINS.has(domain)) {
    return {
      valid: false,
      reason:
        "Please use a valid email address. Temporary/disposable emails are not allowed.",
    };
  }

  return { valid: true };
}
